```{r}
library(readr)
library(dplyr)
library(ggplot2)
str(PlantGrowth)
head(PlantGrowth)
summary(PlantGrowth)
```

```{r}
missing_values <- sapply(PlantGrowth, function(x) sum(is.na(x)))
print(missing_values)
```

```{r}
# Visualize the data
# Histogram for numerical variables
num_vars <- sapply(PlantGrowth, is.numeric)
num_data <- PlantGrowth[, num_vars]
```

```{r}
# boxplot
ggplot(PlantGrowth, aes(x =weight, y =group)) +
  geom_boxplot(fill = "orange", color = "black") +
  theme_minimal() +
  labs(title = "Boxplot of Humidity by Season", x= "weight", y= "group")
```

```{r}
# Scatter plot to show the relationship between two numeric variables (replace 'temp' and 'humidity' with appropriate column names)
ggplot(PlantGrowth, aes(x = weight, y = group)) +
  geom_point(color = "red") +
  theme_minimal() +
  labs(title = "Scatter Plot of Temperature vs Humidity", x = "loan_amount", y = "property_value")
```

```{r}
# Time series plot for a variable over time (replace 'date' and 'temp' with appropriate column names)
ggplot(PlantGrowth, aes(x = weight , y = group)) +
  geom_line(color = "blue") +
  theme_minimal() +
  labs(title = "weight vs group", x = "weight", y = "group")
```


